# Generated by Django 4.2 on 2023-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(blank=True, max_length=255, verbose_name='Миниатюра поста'),
        ),
    ]
