# Generated by Django 4.2 on 2023-04-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paid_curse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость курса')),
                ('post_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.post')),
            ],
        ),
    ]
